/**
 * Generate Project API - Creates downloadable project files from code
 * Supports HTML, React, and combined projects
 */

export default async function handler(req, res) {
  // CORS
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

  if (req.method === 'OPTIONS') return res.status(204).end();
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' });

  try {
    const { blocks, projectType = 'auto' } = req.body || {};

    if (!blocks || !Array.isArray(blocks) || blocks.length === 0) {
      return res.status(400).json({ error: 'Code blocks are required' });
    }

    // Determine project type
    const hasReact = blocks.some(b =>
      ['jsx', 'tsx', 'react'].includes(b.language?.toLowerCase())
    );
    const type = projectType === 'auto' ? (hasReact ? 'react' : 'html') : projectType;

    let files = [];

    if (type === 'react') {
      files = generateReactProject(blocks);
    } else {
      files = generateHTMLProject(blocks);
    }

    return res.status(200).json({ files, projectType: type });

  } catch (error) {
    console.error('Generate project error:', error.message || error);
    return res.status(500).json({
      error: error.message || 'Failed to generate project',
    });
  }
}

function generateHTMLProject(blocks) {
  const htmlBlocks = blocks.filter(b => ['html', 'htm'].includes(b.language?.toLowerCase()));
  const cssBlocks = blocks.filter(b => ['css', 'scss', 'sass'].includes(b.language?.toLowerCase()));
  const jsBlocks = blocks.filter(b => ['js', 'javascript'].includes(b.language?.toLowerCase()));

  const files = [];

  // Create index.html
  let indexHtml = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>TabKeep Project</title>
  ${cssBlocks.length > 0 ? '<link rel="stylesheet" href="styles.css">' : ''}
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; }
  </style>
</head>
<body>
${htmlBlocks.map(b => b.code).join('\n\n') || '<div id="app"></div>'}
${jsBlocks.length > 0 ? '<script src="script.js"></script>' : ''}
</body>
</html>`;

  files.push({ name: 'index.html', content: indexHtml });

  // Create styles.css if there's CSS
  if (cssBlocks.length > 0) {
    files.push({
      name: 'styles.css',
      content: cssBlocks.map(b => b.code).join('\n\n'),
    });
  }

  // Create script.js if there's JavaScript
  if (jsBlocks.length > 0) {
    files.push({
      name: 'script.js',
      content: jsBlocks.map(b => b.code).join('\n\n'),
    });
  }

  // Create README
  files.push({
    name: 'README.md',
    content: `# TabKeep Generated Project

## Getting Started

Simply open \`index.html\` in your browser.

## Files

${files.map(f => `- \`${f.name}\``).join('\n')}

---
Generated by [TabKeep](https://tabkeep.app)
`,
  });

  return files;
}

function generateReactProject(blocks) {
  const reactBlocks = blocks.filter(b =>
    ['jsx', 'tsx', 'react'].includes(b.language?.toLowerCase())
  );
  const cssBlocks = blocks.filter(b =>
    ['css', 'scss', 'sass'].includes(b.language?.toLowerCase())
  );

  const files = [];

  // package.json
  files.push({
    name: 'package.json',
    content: JSON.stringify({
      name: 'tabkeep-project',
      private: true,
      version: '0.1.0',
      type: 'module',
      scripts: {
        dev: 'vite',
        build: 'vite build',
        preview: 'vite preview',
      },
      dependencies: {
        react: '^18.2.0',
        'react-dom': '^18.2.0',
      },
      devDependencies: {
        '@vitejs/plugin-react': '^4.2.0',
        vite: '^5.0.0',
      },
    }, null, 2),
  });

  // vite.config.js
  files.push({
    name: 'vite.config.js',
    content: `import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
  plugins: [react()],
})
`,
  });

  // index.html
  files.push({
    name: 'index.html',
    content: `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>TabKeep Project</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>
`,
  });

  // src/main.jsx
  files.push({
    name: 'src/main.jsx',
    content: `import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App'
import './index.css'

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
)
`,
  });

  // src/App.jsx - use the React code from blocks
  const appCode = reactBlocks.length > 0
    ? reactBlocks[0].code
    : `function App() {
  return (
    <div>
      <h1>Hello from TabKeep!</h1>
    </div>
  )
}

export default App`;

  files.push({
    name: 'src/App.jsx',
    content: appCode.includes('export default') ? appCode : appCode + '\n\nexport default App;',
  });

  // src/index.css
  files.push({
    name: 'src/index.css',
    content: cssBlocks.length > 0
      ? cssBlocks.map(b => b.code).join('\n\n')
      : `* {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}

body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
  line-height: 1.5;
}
`,
  });

  // Additional component files
  reactBlocks.slice(1).forEach((block, index) => {
    const componentName = extractComponentName(block.code) || `Component${index + 1}`;
    files.push({
      name: `src/${componentName}.jsx`,
      content: block.code,
    });
  });

  // README
  files.push({
    name: 'README.md',
    content: `# TabKeep Generated React Project

## Getting Started

\`\`\`bash
npm install
npm run dev
\`\`\`

Then open http://localhost:5173 in your browser.

## Build for Production

\`\`\`bash
npm run build
\`\`\`

---
Generated by [TabKeep](https://tabkeep.app)
`,
  });

  return files;
}

function extractComponentName(code) {
  // Try to find component name from code
  const patterns = [
    /function\s+(\w+)/,
    /const\s+(\w+)\s*=/,
    /class\s+(\w+)/,
    /export\s+default\s+(\w+)/,
  ];

  for (const pattern of patterns) {
    const match = code.match(pattern);
    if (match && match[1]) {
      return match[1];
    }
  }

  return null;
}
